import { readFileSync } from 'fs';

export enum ModelHead {
  id = 0,
  name = 1,
  created = 2,
  description = 3,
  contextLength = 4,
  requestLimits = 5,
  modality = 6,
  tokenizer = 7,
  instructType = 8,
  costPrompt = 9,
  costCompletion = 10,
  costImage = 11,
  costRequest = 12,
  contextLengthTopProvider = 13,
  maxCompletionTokensTopProvider = 14,
  isModerated = 15,
  preferredProvider = 16,
  type = 17,
  incompatible = 18
}

export interface Model {
  id: string;
  name: string;
  created: number;
  description: string;
  contextLength: number;
  // requests per minute
  requestLimits: number;
  modality: string;
  tokenizer: string;
  instructType: string;
  costPrompt: number;
  costCompletion: number;
  costImage: number;
  costRequest: number;
  contextLengthTopProvider: number;
  maxCompletionTokensTopProvider: number;
  isModerated: boolean;
  preferredProvider: string;
  type: string;
  incompatible: string[];
}

export const claudeDesc = "Anthropic's model for low-latency, high throughput text generation. Supports hundreds of pages of text.";
export const gptDesc = "GPT-3.5 Turbo is OpenAI's fastest model. It can understand and generate natural language or code, and is optimized for chat and traditional completion tasks. Training data up to Sep 2021.";
export const openaiDesc = "The latest and strongest model family from OpenAI, o1 is designed to spend more time thinking before responding. The o1 models are optimized for math, science, programming, and other STEM-related tasks. They consistently exhibit PhD-level accuracy on benchmarks in physics, chemistry, and biology. Learn more in the [launch announcement](https://openai.com/o1). Note: This model is currently experimental and not suitable for production use-cases, and may be heavily rate-limited.";

// Models data defined as TypeScript objects
// Convert Python models array to TypeScript
// Models data defined as TypeScript objects
export const models: Model[] = [
  {
    id: "meta-llama/llama-3.1-405b",
    name: "Meta: Llama 3.1 405B (base)",
    created: 1722556800,
    description: "Meta's latest class of model (Llama 3.1) launched with a variety of sizes & flavors. This is the base 405B pre-trained version. It has demonstrated strong performance compared to leading closed-source models in human evaluations.",
    contextLength: 131072,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Llama3",
    instructType: "none",
    costPrompt: 2e-06,
    costCompletion: 2e-06,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32768,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "nothingiisreal/mn-celeste-12b",
    name: "Mistral Nemo 12B Celeste",
    created: 1722556800,
    description: "A specialized story writing and roleplaying model based on Mistral's NeMo 12B Instruct. Fine-tuned on curated datasets including Reddit Writing Prompts and Opus Instruct 25K. This model excels at creative writing, offering improved NSFW capabilities, with smarter and more active narration. It demonstrates remarkable versatility in both SFW and NSFW scenarios, with strong Out of Character (OOC) steering capabilities, allowing fine-tuned control over narrative direction and character behavior. Check out the model's [HuggingFace page](https://huggingface.co/nothingiisreal/MN-12B-Celeste-V1.9) for details on what parameters and prompts work best!",
    contextLength: 32000,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Mistral",
    instructType: "chatml",
    costPrompt: 1.5e-06,
    costCompletion: 1.5e-06,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32000,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "liquid/lfm-40b",
    name: "Liquid: LFM 40B MoE",
    created: 1727654400,
    description: "Liquid's 40.3B Mixture of Experts (MoE) model. Liquid Foundation Models (LFMs) are large neural networks built with computational units rooted in dynamic systems. LFMs are general-purpose AI models that can be used to model any kind of sequential data, including video, audio, text, time series, and signals. See the [launch announcement](https://www.liquid.ai/liquid-foundation-models) for benchmarks and more info.",
    contextLength: 32768,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Other",
    instructType: "vicuna",
    costPrompt: 0,
    costCompletion: 0,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32768,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "thedrummer/rocinante-12b",
    name: "Rocinante 12B",
    created: 1727654400,
    description: "Rocinante 12B is designed for engaging storytelling and rich prose. Early testers have reported: - Expanded vocabulary with unique and expressive word choices - Enhanced creativity for vivid narratives - Adventure-filled and captivating stories",
    contextLength: 32768,
    requestLimits: 0,
    modality: "text->text", 
    tokenizer: "Qwen",
    instructType: "chatml",
    costPrompt: 2.5e-7,
    costCompletion: 5e-7,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32768,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "eva-unit-01/eva-qwen-2.5-14b",
    name: "EVA Qwen2.5 14B",
    created: 1727654400,
    description: "A model specializing in RP and creative writing, this model is based on Qwen2.5-14B, fine-tuned with a mixture of synthetic and natural data. It is trained on 1.5M tokens of role-play data, and fine-tuned on 1.5M tokens of synthetic data.",
    contextLength: 32768,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Qwen",
    instructType: "chatml", 
    costPrompt: 2.5e-7,
    costCompletion: 5e-7,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32768,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "openai/gpt-3.5-turbo",
    name: "GPT-3.5 Turbo",
    created: 1679584800,
    description: "OpenAI's GPT-3.5 Turbo language model.",
    contextLength: 4096,
    requestLimits: 1,
    modality: "text->text",
    tokenizer: "gpt-3",
    instructType: "gpt",
    costPrompt: 0.002,
    costCompletion: 0.004,
    costImage: 0,
    costRequest: 0.002,
    contextLengthTopProvider: 4096,
    maxCompletionTokensTopProvider: 1024,
    isModerated: true,
    preferredProvider: "openai",
    type: "llm",
    incompatible: []
  },
  {
    id: "openai/gpt-4",
    name: "GPT-4",
    created: 1679584800,
    description: "OpenAI's GPT-4 language model.",
    contextLength: 8192,
    requestLimits: 1,
    modality: "text->text",
    tokenizer: "gpt-4",
    instructType: "gpt",
    costPrompt: 0.03,
    costCompletion: 0.06,
    costImage: 0,
    costRequest: 0.03,
    contextLengthTopProvider: 8192,
    maxCompletionTokensTopProvider: 2048,
    isModerated: true,
    preferredProvider: "openai",
    type: "llm",
    incompatible: []
  },
  {
    id: "anthropic/claude-2",
    name: "Claude 2",
    created: 1679584800,
    description: "Anthropic's Claude 2 language model.",
    contextLength: 16384,
    requestLimits: 1,
    modality: "text->text",
    tokenizer: "claude",
    instructType: "claude",
    costPrompt: 0.008,
    costCompletion: 0.024,
    costImage: 0,
    costRequest: 0.008,
    contextLengthTopProvider: 16384,
    maxCompletionTokensTopProvider: 4096,
    isModerated: true,
    preferredProvider: "anthropic",
    type: "llm",
    incompatible: []
  },
  {
    id: "google/flan-t5-large",
    name: "Flan T5 Large",
    created: 1679584800,
    description: "Google's Flan T5 Large language model.",
    contextLength: 1024,
    requestLimits: 1,
    modality: "text->text",
    tokenizer: "t5",
    instructType: "t5",
    costPrompt: 0.006,
    costCompletion: 0.015,
    costImage: 0,
    costRequest: 0.006,
    contextLengthTopProvider: 1024,
    maxCompletionTokensTopProvider: 512,
    isModerated: true,
    preferredProvider: "google",
    type: "llm",
    incompatible: []
  },
  {
    id: "anthropic/claude-1",
    name: "Claude 1",
    created: 1679584800,
    description: "Anthropic's Claude 1 language model.",
    contextLength: 8192,
    requestLimits: 1,
    modality: "text->text",
    tokenizer: "claude",
    instructType: "claude",
    costPrompt: 0.004,
    costCompletion: 0.012,
    costImage: 0,
    costRequest: 0.004,
    contextLengthTopProvider: 8192,
    maxCompletionTokensTopProvider: 2048,
    isModerated: true,
    preferredProvider: "anthropic",
    type: "llm",
    incompatible: []
  },
  {
    id: "google/flan-t5-base",
    name: "Flan T5 Base",
    created: 1679584800,
    description: "Google's Flan T5 Base language model.",
    contextLength: 512,
    requestLimits: 1,
    modality: "text->text",
    tokenizer: "t5",
    instructType: "t5",
    costPrompt: 0.003,
    costCompletion: 0.0075,
    costImage: 0,
    costRequest: 0.003,
    contextLengthTopProvider: 512,
    maxCompletionTokensTopProvider: 256,
    isModerated: true,
    preferredProvider: "google",
    type: "llm",
    incompatible: []
  },
  {
    id: "anthropic/claude-instant-1.1",
    name: "Claude Instant v1.1",
    created: 1700611200,
    description: claudeDesc,
    contextLength: 100000,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Claude",
    instructType: "claude",
    costPrompt: 8e-07,
    costCompletion: 2.4e-06,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 100000,
    maxCompletionTokensTopProvider: 2048,
    isModerated: true,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "anthropic/claude-2.1",
    name: "Claude v2.1",
    created: 1700611200,
    description: "Claude 2 delivers advancements in key capabilities for enterprises—including an industry-leading 200K token context window, significant reductions in rates of model hallucination, system prompts and a new beta feature: tool use.",
    contextLength: 200000,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Claude",
    instructType: "nan",
    costPrompt: 8e-06,
    costCompletion: 2.4e-05,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 200000,
    maxCompletionTokensTopProvider: 4096,
    isModerated: true,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "anthropic/claude-2.1:beta",
    name: "Claude v2.1 (self-moderated)",
    created: 1700611200,
    description: "Claude 2 delivers advancements in key capabilities for enterprises—including an industry-leading 200K token context window, significant reductions in rates of model hallucination, system prompts and a new beta feature: tool use._This is a faster endpoint, made available in collaboration with Anthropic, that is self-moderated: response moderation happens on the provider's side instead of OpenRouter's. For requests that pass moderation, it's identical to the [Standard](/models/anthropic/claude-2.1) variant._",
    contextLength: 200000,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Claude",
    instructType: "nan",
    costPrompt: 8e-06,
    costCompletion: 2.4e-05,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 200000,
    maxCompletionTokensTopProvider: 4096,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "anthropic/claude-3.5-sonnet",
    name: "Anthropic: Claude 3.5 Sonnet",
    created: 1718841600,
    description: "Claude 3.5 Sonnet delivers better-than-Opus capabilities, faster-than-Sonnet speeds, at the same Sonnet prices. Sonnet is particularly good at: - Coding: Autonomously writes, edits, and runs code with reasoning and troubleshooting - Data science: Augments human data science expertise; navigates unstructured data while using multiple tools for insights - Visual processing: excelling at interpreting charts, graphs, and images, accurately transcribing text to derive insights beyond just the text alone - Agentic tasks: exceptional tool use, making it great at agentic tasks (i.e. complex, multi-step problem solving tasks that require engaging with other systems) #multimodal",
    contextLength: 200000,
    requestLimits: 0,
    modality: "text+image->text",
    tokenizer: "Claude",
    instructType: "nan",
    costPrompt: 3e-06,
    costCompletion: 1.5e-05,
    costImage: 0.0048,
    costRequest: 0,
    contextLengthTopProvider: 200000,
    maxCompletionTokensTopProvider: 8192,
    isModerated: true,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "anthropic/claude-3.5-sonnet:beta",
    name: "Anthropic: Claude 3.5 Sonnet (self-moderated)", 
    created: 1718841600,
    description: "Claude 3.5 Sonnet delivers better-than-Opus capabilities, faster-than-Sonnet speeds, at the same Sonnet prices. Sonnet is particularly good at: - Coding: Autonomously writes, edits, and runs code with reasoning and troubleshooting - Data science: Augments human data science expertise; navigates unstructured data while using multiple tools for insights - Visual processing: excelling at interpreting charts, graphs, and images, accurately transcribing text to derive insights beyond just the text alone - Agentic tasks: exceptional tool use, making it great at agentic tasks (i.e. complex, multi-step problem solving tasks that require engaging with other systems) #multimodal_This is a faster endpoint, made available in collaboration with Anthropic, that is self-moderated: response moderation happens on the provider's side instead of OpenRouter's. For requests that pass moderation, it's identical to the [Standard](/models/anthropic/claude-3.5-sonnet) variant._",
    contextLength: 200000,
    requestLimits: 0,
    modality: "text+image->text",
    tokenizer: "Claude",
    instructType: "nan", 
    costPrompt: 3e-06,
    costCompletion: 1.5e-05,
    costImage: 0.0048,
    costRequest: 0,
    contextLengthTopProvider: 200000,
    maxCompletionTokensTopProvider: 8192,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "sao10k/l3-euryale-70b",
    name: "Llama 3 Euryale 70B v2.1",
    created: 1718668800,
    description: "Euryale 70B v2.1 is a model focused on creative roleplay from [Sao10k](https://ko-fi.com/sao10k). - Better prompt adherence. - Better anatomy / spatial awareness. - Adapts much better to unique and custom formatting / reply formats. - Very creative, lots of unique swipes. - Is not restrictive during roleplays.",
    contextLength: 8192,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Llama3",
    instructType: "llama3",
    costPrompt: 3.5e-07,
    costCompletion: 4e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 8192,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "cognitivecomputations/dolphin-mixtral-8x22b",
    name: "Dolphin 2.9.2 Mixtral 8x22B 🐬",
    created: 1717804800,
    description: "Dolphin 2.9 is designed for instruction following, conversational, and coding. This model is a finetune of [Mixtral 8x22B Instruct](/models/mistralai/mixtral-8x22b-instruct). It features a 64k context length and was fine-tuned with a 16k sequence length using ChatML templates. This model is a successor to [Dolphin Mixtral 8x7B](/models/cognitivecomputations/dolphin-mixtral-8x7b). The model is uncensored and is stripped of alignment and bias. It requires an external alignment layer for ethical use. Users are cautioned to use this highly compliant model responsibly, as detailed in a blog post about uncensored models at [erichartford.com/uncensored-models](https://erichartford.com/uncensored-models). #moe #uncensored",
    contextLength: 65536,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Mistral",
    instructType: "chatml",
    costPrompt: 9e-07,
    costCompletion: 9e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 16000,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "qwen/qwen-2-72b-instruct",
    name: "Qwen 2 72B Instruct",
    created: 1717718400,
    description: "Qwen2 72B is a transformer-based model that excels in language understanding, multilingual capabilities, coding, mathematics, and reasoning. It features SwiGLU activation, attention QKV bias, and group query attention. It is pretrained on extensive data with supervised finetuning and direct preference optimization. For more details, see this [blog post](https://qwenlm.github.io/blog/qwen2/) and [GitHub repo](https://github.com/QwenLM/Qwen2).",
    contextLength: 32768,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Qwen",
    instructType: "chatml",
    costPrompt: 3.4e-07,
    costCompletion: 3.9e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32768,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "google/gemini-pro-1.5-exp",
    name: "Google: Gemini Pro 1.5 Experimental",
    created: 1722470400,
    description: "Gemini 1.5 Pro (0827) is an experimental version of the [Gemini 1.5 Pro](/models/google/gemini-pro-1.5) model. #multimodal Note: This model is currently experimental and not suitable for production use-cases, and may be heavily rate-limited.",
    contextLength: 1000000,
    requestLimits: 0,
    modality: "text+image->text",
    tokenizer: "Gemini",
    instructType: "nan",
    costPrompt: 0,
    costCompletion: 0,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 1000000,
    maxCompletionTokensTopProvider: 8192,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "perplexity/llama-3.1-sonar-large-128k-online",
    name: "Perplexity: Llama 3.1 Sonar 70B Online",
    created: 1722470400,
    description: "Llama 3.1 Sonar is Perplexity's latest model family. It surpasses their earlier Sonar models in cost-efficiency, speed, and performance. This is the online version of the [offline chat model](/models/perplexity/llama-3.1-sonar-large-128k-chat). It is focused on delivering helpful, up-to-date, and factual responses. #online",
    contextLength: 127072,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Llama3",
    instructType: "nan",
    costPrompt: 1e-06,
    costCompletion: 1e-06,
    costImage: 0,
    costRequest: 0.005,
    contextLengthTopProvider: 127072,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "perplexity/llama-3.1-sonar-large-128k-chat",
    name: "Perplexity: Llama 3.1 Sonar 70B",
    created: 1722470400,
    description: "Llama 3.1 Sonar is Perplexity's latest model family. It surpasses their earlier Sonar models in cost-efficiency, speed, and performance. This is a normal offline LLM, but the [online version](/models/perplexity/llama-3.1-sonar-large-128k-online) of this model has Internet access.",
    contextLength: 131072,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Llama3",
    instructType: "nan",
    costPrompt: 1e-06,
    costCompletion: 1e-06,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 131072,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "perplexity/llama-3.1-sonar-small-128k-online",
    name: "Perplexity: Llama 3.1 Sonar 8B Online",
    created: 1722470400,
    description: "Llama 3.1 Sonar is Perplexity's latest model family. It surpasses their earlier Sonar models in cost-efficiency, speed, and performance. This is the online version of the [offline chat model](/models/perplexity/llama-3.1-sonar-small-128k-chat). It is focused on delivering helpful, up-to-date, and factual responses. #online",
    contextLength: 127072,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Llama3", 
    instructType: "nan",
    costPrompt: 2e-07,
    costCompletion: 2e-07,
    costImage: 0,
    costRequest: 0.005,
    contextLengthTopProvider: 127072,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "perplexity/llama-3.1-sonar-small-128k-chat",
    name: "Perplexity: Llama 3.1 Sonar 8B",
    created: 1722470400,
    description: "Llama 3.1 Sonar is Perplexity's latest model family. It surpasses their earlier Sonar models in cost-efficiency, speed, and performance. This is a normal offline LLM, but the [online version](/models/perplexity/llama-3.1-sonar-small-128k-online) of this model has Internet access.",
    contextLength: 131072,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Llama3",
    instructType: "nan",
    costPrompt: 2e-07,
    costCompletion: 2e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 131072,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "meta-llama/llama-3.1-70b-instruct",
    name: "Meta: Llama 3.1 70B Instruct",
    created: 1721692800,
    description: "Meta's latest class of model (Llama 3.1) launched with a variety of sizes & flavors. This 70B instruct-tuned version is optimized for high quality dialogue usecases. It has demonstrated strong performance compared to leading closed-source models in human evaluations.",
    contextLength: 131072,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Llama3",
    instructType: "llama3",
    costPrompt: 3e-07,
    costCompletion: 3e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 131072,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "meta-llama/llama-3.1-8b-instruct",
    name: "Meta: Llama 3.1 8B Instruct", 
    created: 1721692800,
    description: "Meta's latest class of model (Llama 3.1) launched with a variety of sizes & flavors. This 8B instruct-tuned version is fast and efficient. It has demonstrated strong performance compared to leading closed-source models in human evaluations.",
    contextLength: 131072,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Llama3",
    instructType: "llama3",
    costPrompt: 5.5e-08,
    costCompletion: 5.5e-08,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 100000,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "meta-llama/llama-3.1-405b-instruct",
    name: "Meta: Llama 3.1 405B Instruct",
    created: 1721692800,
    description: "The highly anticipated 400B class of Llama3 is here! Clocking in at 128k context with impressive eval scores, the Meta AI team continues to push the frontier of open-source LLMs. Meta's latest class of model (Llama 3.1) launched with a variety of sizes & flavors. This 405B instruct-tuned version is optimized for high quality dialogue usecases. It has demonstrated strong performance compared to leading closed-source models in human evaluations.",
    contextLength: 131072,
    requestLimits: 0,
    modality: "text->text", 
    tokenizer: "Llama3",
    instructType: "llama3",
    costPrompt: 1.79e-06,
    costCompletion: 1.79e-06,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32000,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "mistralai/codestral-mamba",
    name: "Mistral: Codestral Mamba",
    created: 1721347200,
    description: "A 7.3B parameter Mamba-based model designed for code and reasoning tasks. - Linear time inference, allowing for theoretically infinite sequence lengths - 256k token context window - Optimized for quick responses, especially beneficial for code productivity - Performs comparably to state-of-the-art transformer models in code and reasoning tasks - Available under the Apache 2.0 license for free use, modification, and distribution",
    contextLength: 256000,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Mistral",
    instructType: "mistral",
    costPrompt: 2.5e-07,
    costCompletion: 2.5e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 256000,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "mistralai/mistral-nemo",
    name: "Mistral: Mistral Nemo",
    created: 1721347200, 
    description: "A 12B parameter model with a 128k token context length built by Mistral in collaboration with NVIDIA. The model is multilingual, supporting English, French, German, Spanish, Italian, Portuguese, Chinese, Japanese, Korean, Arabic, and Hindi. It supports function calling and is released under the Apache 2.0 license.",
    contextLength: 128000,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Mistral",
    instructType: "mistral",
    costPrompt: 1.3e-07,
    costCompletion: 1.3e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 128000,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "openai/gpt-4o-mini-2024-07-18",
    name: "OpenAI: GPT-4o-mini (2024-07-18)",
    created: 1721260800,
    description: "GPT-4o mini is OpenAI's newest model after [GPT-4 Omni](/models/openai/gpt-4o), supporting both text and image inputs with text outputs. As their most advanced small model, it is many multiples more affordable than other recent frontier models, and more than 60% cheaper than [GPT-3.5 Turbo](/models/openai/gpt-3.5-turbo). It maintains SOTA intelligence, while being significantly more cost-effective. GPT-4o mini achieves an 82% score on MMLU and presently ranks higher than GPT-4 on chat preferences [common leaderboards](https://arena.lmsys.org/). Check out the [launch announcement](https://openai.com/index/gpt-4o-mini-advancing-cost-efficient-intelligence/) to learn more.",
    contextLength: 128000,
    requestLimits: 0,
    modality: "text+image->text",
    tokenizer: "GPT",
    instructType: "nan",
    costPrompt: 1.5e-07,
    costCompletion: 6e-07,
    costImage: 0.007225,
    costRequest: 0,
    contextLengthTopProvider: 128000,
    maxCompletionTokensTopProvider: 16384,
    isModerated: true,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "qwen/qwen-2-7b-instruct",
    name: "Qwen 2 7B Instruct",
    created: 1721088000,
    description: "Qwen2 7B is a transformer-based model that excels in language understanding, multilingual capabilities, coding, mathematics, and reasoning. It features SwiGLU activation, attention QKV bias, and group query attention. It is pretrained on extensive data with supervised finetuning and direct preference optimization. For more details, see this [blog post](https://qwenlm.github.io/blog/qwen2/) and [GitHub repo](https://github.com/QwenLM/Qwen2).",
    contextLength: 32768,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Qwen",
    instructType: "chatml",
    costPrompt: 5.4e-08,
    costCompletion: 5.4e-08,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32768,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "google/gemma-2-27b-it",
    name: "Google: Gemma 2 27B",
    created: 1720828800,
    description: "Gemma 2 27B by Google is an open model built from the same research and technology used to create the [Gemini models](/models?q=gemini). Gemma models are well-suited for a variety of text generation tasks, including question answering, summarization, and reasoning. See the [launch announcement](https://blog.google/technology/developers/google-gemma-2/) for more details.",
    contextLength: 8192,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Gemini",
    instructType: "gemma",
    costPrompt: 2.7e-07,
    costCompletion: 2.7e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 8192,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "alpindale/magnum-72b",
    name: "Magnum 72B",
    created: 1720656000,
    description: "From the maker of [Goliath](https://openrouter.ai/models/alpindale/goliath-120b), Magnum 72B is the first in a new family of models designed to achieve the prose quality of the Claude 3 models, notably Opus & Sonnet. The model is based on [Qwen2 72B](https://openrouter.ai/models/qwen/qwen-2-72b-instruct) and trained with 55 million tokens of highly curated roleplay (RP) data.",
    contextLength: 16384,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Qwen",
    instructType: "chatml",
    costPrompt: 3.75e-06,
    costCompletion: 4.5e-06,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 16384,
    maxCompletionTokensTopProvider: 1024,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "nousresearch/hermes-2-theta-llama-3-8b",
    name: "Nous: Hermes 2 Theta 8B",
    created: 1720656000,
    description: "An experimental merge model based on Llama 3, exhibiting a very distinctive style of writing. It combines the the best of [Meta's Llama 3 8B](https://openrouter.ai/models/meta-llama/llama-3-8b-instruct) and Nous Research's [Hermes 2 Pro](https://openrouter.ai/models/nousresearch/hermes-2-pro-llama-3-8b). Hermes-2 Θ (theta) was specifically designed with a few capabilities in mind: executing function calls, generating JSON output, and most remarkably, demonstrating metacognitive abilities (contemplating the nature of thought and recognizing the diversity of cognitive processes among individuals).",
    contextLength: 16384,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Llama3",
    instructType: "chatml",
    costPrompt: 1.875e-07,
    costCompletion: 1.125e-06,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 16384,
    maxCompletionTokensTopProvider: 2048,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "google/gemini-flash-8b-1.5-exp",
    name: "Google: Gemini Flash 8B 1.5 Experimental",
    created: 1724803200,
    description: "Gemini 1.5 Flash 8B Experimental is an experimental, 8B parameter version of the [Gemini 1.5 Flash](/models/google/gemini-flash-1.5) model. #multimodal Note: This model is currently experimental and not suitable for production use-cases, and may be heavily rate-limited.",
    contextLength: 1000000,
    requestLimits: 0,
    modality: "text+image->text",
    tokenizer: "Gemini",
    instructType: "nan",
    costPrompt: 0,
    costCompletion: 0,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 1000000,
    maxCompletionTokensTopProvider: 8192,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "sao10k/l3-euryale-70b",
    name: "Llama 3.1 Euryale 70B v2.2",
    created: 1724803200,
    description: "Euryale L3.1 70B v2.2 is a model focused on creative roleplay from [Sao10k](https://ko-fi.com/sao10k). It is the successor of [Euryale L3 70B v2.1](/models/sao10k/l3-euryale-70b).",
    contextLength: 8192,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Llama3",
    instructType: "llama3",
    costPrompt: 3.5e-07,
    costCompletion: 4e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 128000,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "google/gemini-flash-1.5-exp",
    name: "Google: Gemini Flash 1.5 Experimental",
    created: 1724803200,
    description: "Gemini 1.5 Flash Experimental is an experimental version of the [Gemini 1.5 Flash](/models/google/gemini-flash-1.5) model. #multimodal Note: This model is currently experimental and not suitable for production use-cases, and may be heavily rate-limited.",
    contextLength: 1000000,
    requestLimits: 0,
    modality: "text+image->text",
    tokenizer: "Gemini",
    instructType: "nan",
    costPrompt: 0,
    costCompletion: 0,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 1000000,
    maxCompletionTokensTopProvider: 8192,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "ai21/jamba-1-5-large",
    name: "AI21: Jamba 1.5 Large",
    created: 1724371200,
    description: "Jamba 1.5 Large is part of AI21's new family of open models, offering superior speed, efficiency, and quality. It features a 256K effective context window, the longest among open models, enabling improved performance on tasks like document summarization and analysis. Built on a novel SSM-Transformer architecture, it outperforms larger models like Llama 3.1 70B on benchmarks while maintaining resource efficiency. Read their [announcement](https://www.ai21.com/blog/announcing-jamba-model-family) to learn more.",
    contextLength: 256000,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Other",
    instructType: "nan",
    costPrompt: 2e-06,
    costCompletion: 8e-06,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 256000,
    maxCompletionTokensTopProvider: 4096,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "ai21/jamba-1-5-mini",
    name: "AI21: Jamba 1.5 Mini",
    created: 1724371200,
    description: "Jamba 1.5 Mini is the world's first production-grade Mamba-based model, combining SSM and Transformer architectures for a 256K context window and high efficiency. It works with 9 languages and can handle various writing and analysis tasks as well as or better than similar small models. This model uses less computer memory and works faster with longer texts than previous designs. Read their [announcement](https://www.ai21.com/blog/announcing-jamba-model-family) to learn more.",
    contextLength: 256000,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Other",
    instructType: "nan",
    costPrompt: 2e-07,
    costCompletion: 4e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 256000,
    maxCompletionTokensTopProvider: 4096,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "microsoft/phi-3-mini-128k-instruct",
    name: "Phi-3 Mini 128K Instruct",
    created: 1716681600,
    description: "Phi-3 Mini is a powerful 3.8B parameter model designed for advanced language understanding, reasoning, and instruction following. Optimized through supervised fine-tuning and preference adjustments, it excels in tasks involving common sense, mathematics, logical reasoning, and code processing. At time of release, Phi-3 Medium demonstrated state-of-the-art performance among lightweight models. This model is static, trained on an offline dataset with an October 2023 cutoff date.",
    contextLength: 128000,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Other",
    instructType: "phi3",
    costPrompt: 1e-07,
    costCompletion: 1e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 128000,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "microsoft/phi-3-medium-128k-instruct",
    name: "Phi-3 Medium 128K Instruct",
    created: 1716508800,
    description: "Phi-3 128K Medium is a powerful 14-billion parameter model designed for advanced language understanding, reasoning, and instruction following. Optimized through supervised fine-tuning and preference adjustments, it excels in tasks involving common sense, mathematics, logical reasoning, and code processing. At time of release, Phi-3 Medium demonstrated state-of-the-art performance among lightweight models. In the MMLU-Pro eval, the model even comes close to a Llama3 70B level of performance.",
    contextLength: 128000,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Other",
    instructType: "phi3",
    costPrompt: 1e-06,
    costCompletion: 1e-06,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 128000,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "neversleep/llama-3-lumimaid-70b",
    name: "Llama 3 Lumimaid 70B",
    created: 1715817600,
    description: "The NeverSleep team is back, with a Llama 3 70B finetune trained on their curated roleplay data. Striking a balance between eRP and RP, Lumimaid was designed to be serious, yet uncensored when necessary. To enhance it's overall intelligence and chat capability, roughly 40% of the training data was not roleplay. This provides a breadth of knowledge to access, while still keeping roleplay as the primary strength.",
    contextLength: 8192,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Llama3",
    instructType: "llama3",
    costPrompt: 3.375e-06,
    costCompletion: 4.5e-06,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 8192,
    maxCompletionTokensTopProvider: 2048,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "google/gemini-flash-1.5",
    name: "Google: Gemini Flash 1.5",
    created: 1715644800,
    description: "Gemini 1.5 Flash is a foundation model that performs well at a variety of multimodal tasks such as visual understanding, classification, summarization, and creating content from image, audio and video. It's adept at processing visual and text inputs such as photographs, documents, infographics, and screenshots. Gemini 1.5 Flash is designed for high-volume, high-frequency tasks where cost and latency matter. On most common tasks, Flash achieves comparable quality to other Gemini Pro models at a significantly reduced cost. Flash is well-suited for applications like chat assistants and on-demand content generation where speed and scale matter. #multimodal",
    contextLength: 1000000,
    requestLimits: 0,
    modality: "text+image->text",
    tokenizer: "Gemini",
    instructType: "nan",
    costPrompt: 7.5e-08,
    costCompletion: 3e-07,
    costImage: 4e-05,
    costRequest: 0,
    contextLengthTopProvider: 1000000,
    maxCompletionTokensTopProvider: 8192,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "deepseek/deepseek-chat",
    name: "DeepSeek V2.5",
    created: 1715644800,
    description: "DeepSeek-V2.5 is an upgraded version that combines DeepSeek-V2-Chat and DeepSeek-Coder-V2-Instruct. The new model integrates the general and coding abilities of the two previous versions. DeepSeek-V2 Chat is a conversational finetune of DeepSeek-V2, a Mixture-of-Experts (MoE) language model. It comprises 236B total parameters, of which 21B are activated for each token. Compared with DeepSeek 67B, DeepSeek-V2 achieves stronger performance, and meanwhile saves 42.5% of training costs, reduces the KV cache by 93.3%, and boosts the maximum generation throughput to 5.76 times.",
    contextLength: 128000,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Other",
    instructType: "nan",
    costPrompt: 1.4e-07,
    costCompletion: 2.8e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 128000,
    maxCompletionTokensTopProvider: 4096,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "perplexity/llama-3-sonar-large-32k-online",
    name: "Perplexity: Llama3 Sonar 70B Online",
    created: 1715644800,
    description: "Llama3 Sonar is Perplexity's latest model family. It surpasses their earlier Sonar models in cost-efficiency, speed, and performance. This is the online version of the [offline chat model](/models/perplexity/llama-3-sonar-large-32k-chat). It is focused on delivering helpful, up-to-date, and factual responses. #online",
    contextLength: 28000,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Llama3",
    instructType: "nan",
    costPrompt: 1e-06,
    costCompletion: 1e-06,
    costImage: 0,
    costRequest: 0.005,
    contextLengthTopProvider: 28000,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "perplexity/llama-3-sonar-large-32k-chat",
    name: "Perplexity: Llama3 Sonar 70B",
    created: 1715644800,
    description: "Llama3 Sonar is Perplexity's latest model family. It surpasses their earlier Sonar models in cost-efficiency, speed, and performance. This is a normal offline LLM, but the [online version](/models/perplexity/llama-3-sonar-large-32k-online) of this model has Internet access.",
    contextLength: 32768,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Llama3",
    instructType: "nan",
    costPrompt: 1e-06,
    costCompletion: 1e-06,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32768,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "perplexity/llama-3-sonar-small-32k-online",
    name: "Perplexity: Llama3 Sonar 8B Online",
    created: 1715644800,
    description: "Llama3 Sonar is Perplexity's latest model family. It surpasses their earlier Sonar models in cost-efficiency, speed, and performance. This is the online version of the [offline chat model](/models/perplexity/llama-3-sonar-small-32k-chat). It is focused on delivering helpful, up-to-date, and factual responses. #online",
    contextLength: 28000,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Llama3",
    instructType: "nan",
    costPrompt: 2e-07,
    costCompletion: 2e-07,
    costImage: 0,
    costRequest: 0.005,
    contextLengthTopProvider: 28000,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "perplexity/llama-3-sonar-small-32k-chat",
    name: "Perplexity: Llama3 Sonar 8B",
    created: 1715644800,
    description: "Llama3 Sonar is Perplexity's latest model family. It surpasses their earlier Sonar models in cost-efficiency, speed, and performance. This is a normal offline LLM, but the [online version](/models/perplexity/llama-3-sonar-small-32k-online) of this model has Internet access.",
    contextLength: 32768,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Llama3",
    instructType: "nan",
    costPrompt: 2e-07,
    costCompletion: 2e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32768,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "meta-llama/llama-guard-2-8b",
    name: "Meta: LlamaGuard 2 8B",
    created: 1715558400,
    description: "This safeguard model has 8B parameters and is based on the Llama 3 family. Just like is predecessor, [LlamaGuard 1](https://huggingface.co/meta-llama/LlamaGuard-7b), it can do both prompt and response classification. LlamaGuard 2 acts as a normal LLM would, generating text that indicates whether the given input/output is safe/unsafe. If deemed unsafe, it will also share the content categories violated. For best results, please use raw prompt input or the `/completions` endpoint, instead of the chat API. It has demonstrated strong performance compared to leading closed-source models in human evaluations.",
    contextLength: 8192,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Llama3",
    instructType: "none",
    costPrompt: 1.8e-07,
    costCompletion: 1.8e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 8192,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "openai/gpt-4o-2024-05-13",
    name: "OpenAI: GPT-4o (2024-05-13)",
    created: 1715558400,
    description: "GPT-4o ('o' for 'omni') is OpenAI's latest AI model, supporting both text and image inputs with text outputs. It maintains the intelligence level of [GPT-4 Turbo](/models/openai/gpt-4-turbo) while being twice as fast and 50% more cost-effective. GPT-4o also offers improved performance in processing non-English languages and enhanced visual capabilities. For benchmarking against other models, it was briefly called ['im-also-a-good-gpt2-chatbot'](https://twitter.com/LiamFedus/status/1790064963966370209)",
    contextLength: 128000,
    requestLimits: 0,
    modality: "text+image->text",
    tokenizer: "GPT",
    instructType: "nan",
    costPrompt: 5e-06,
    costCompletion: 1.5e-05,
    costImage: 0.007225,
    costRequest: 0,
    contextLengthTopProvider: 128000,
    maxCompletionTokensTopProvider: 4096,
    isModerated: true,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "openai/gpt-4o",
    name: "OpenAI: GPT-4o",
    created: 1715558400,
    description: "GPT-4o ('o' for 'omni') is OpenAI's latest AI model, supporting both text and image inputs with text outputs. It maintains the intelligence level of [GPT-4 Turbo](/models/openai/gpt-4-turbo) while being twice as fast and 50% more cost-effective. GPT-4o also offers improved performance in processing non-English languages and enhanced visual capabilities. For benchmarking against other models, it was briefly called ['im-also-a-good-gpt2-chatbot'](https://twitter.com/LiamFedus/status/1790064963966370209)",
    contextLength: 128000,
    requestLimits: 0,
    modality: "text+image->text",
    tokenizer: "GPT",
    instructType: "nan",
    costPrompt: 5e-06,
    costCompletion: 1.5e-05,
    costImage: 0.007225,
    costRequest: 0,
    contextLengthTopProvider: 128000,
    maxCompletionTokensTopProvider: 4096,
    isModerated: true,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "qwen/qwen-72b-chat",
    name: "Qwen 1.5 72B Chat",
    created: 1715212800,
    description: "Qwen1.5 72B is the beta version of Qwen2, a transformer-based decoder-only language model pretrained on a large amount of data. In comparison with the previous released Qwen, the improvements include: - Significant performance improvement in human preference for chat models - Multilingual support of both base and chat models - Stable support of 32K context length for models of all sizes. For more details, see this [blog post](https://qwenlm.github.io/blog/qwen1.5/) and [GitHub repo](https://github.com/QwenLM/Qwen1.5).",
    contextLength: 32768,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Qwen",
    instructType: "chatml",
    costPrompt: 8.1e-07,
    costCompletion: 8.1e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32768,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "qwen/qwen-110b-chat",
    name: "Qwen 1.5 110B Chat", 
    created: 1715212800,
    description: "Qwen1.5 110B is the beta version of Qwen2, a transformer-based decoder-only language model pretrained on a large amount of data. In comparison with the previous released Qwen, the improvements include: - Significant performance improvement in human preference for chat models - Multilingual support of both base and chat models - Stable support of 32K context length for models of all sizes. For more details, see this [blog post](https://qwenlm.github.io/blog/qwen1.5/) and [GitHub repo](https://github.com/QwenLM/Qwen1.5).",
    contextLength: 32768,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Qwen",
    instructType: "chatml",
    costPrompt: 1.62e-06,
    costCompletion: 1.62e-06,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32768,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "neversleep/llama-3-lumimaid-8b",
    name: "Llama 3 Lumimaid 8B",
    created: 1714780800,
    description: "The NeverSleep team is back, with a Llama 3 8B finetune trained on their curated roleplay data. Striking a balance between eRP and RP, Lumimaid was designed to be serious, yet uncensored when necessary. To enhance it's overall intelligence and chat capability, roughly 40% of the training data was not roleplay. This provides a breadth of knowledge to access, while still keeping roleplay as the primary strength.",
    contextLength: 24576,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Llama3",
    instructType: "llama3",
    costPrompt: 1.875e-07,
    costCompletion: 1.125e-06,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 8192,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "sao10k/fimbulvetr-11b-v2",
    name: "Fimbulvetr 11B v2",
    created: 1713657600,
    description: "Creative writing model, routed with permission. It's fast, it keeps the conversation going, and it stays in character. If you submit a raw prompt, you can use Alpaca or Vicuna formats.",
    contextLength: 8192,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Llama2",
    instructType: "alpaca",
    costPrompt: 3.75e-07,
    costCompletion: 1.5e-06,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 8192,
    maxCompletionTokensTopProvider: 2048,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "meta-llama/llama-3-70b-instruct",
    name: "Meta: Llama 3 70B Instruct",
    created: 1713398400,
    description: "Meta's latest class of model (Llama 3) launched with a variety of sizes & flavors. This 70B instruct-tuned version was optimized for high quality dialogue usecases. It has demonstrated strong performance compared to leading closed-source models in human evaluations.",
    contextLength: 8192,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Llama3",
    instructType: "llama3",
    costPrompt: 3.5e-07,
    costCompletion: 4e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 8192,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "meta-llama/llama-3-8b-instruct",
    name: "Meta: Llama 3 8B Instruct",
    created: 1713398400,
    description: "Meta's latest class of model (Llama 3) launched with a variety of sizes & flavors. This 8B instruct-tuned version was optimized for high quality dialogue usecases. It has demonstrated strong performance compared to leading closed-source models in human evaluations.",
    contextLength: 8192,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Llama3",
    instructType: "llama3", 
    costPrompt: 5.5e-08,
    costCompletion: 5.5e-08,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 8192,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "mistralai/mixtral-8x22b-instruct",
    name: "Mistral: Mixtral 8x22B Instruct",
    created: 1713312000,
    description: "Mistral's official instruct fine-tuned version of [Mixtral 8x22B](/models/mistralai/mixtral-8x22b). It uses 39B active parameters out of 141B, offering unparalleled cost efficiency for its size. Its strengths include: - strong math, coding, and reasoning - large context length (64k) - fluency in English, French, Italian, German, and Spanish See benchmarks on the launch announcement [here](https://mistral.ai/news/mixtral-8x22b/). #moe",
    contextLength: 65536,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Mistral",
    instructType: "mistral",
    costPrompt: 9e-07,
    costCompletion: 9e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 65536,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "microsoft/wizardlm-2-7b",
    name: "WizardLM-2 7B",
    created: 1713225600,
    description: "WizardLM-2 7B is the smaller variant of Microsoft AI's latest Wizard model. It is the fastest and achieves comparable performance with existing 10x larger opensource leading models. It is a finetune of [Mistral 7B Instruct](/models/mistralai/mistral-7b-instruct), using the same technique as [WizardLM-2 8x22B](/models/microsoft/wizardlm-2-8x22b). To read more about the model release, [click here](https://wizardlm.github.io/WizardLM2/). #moe",
    contextLength: 32000,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Mistral",
    instructType: "vicuna",
    costPrompt: 5.5e-08,
    costCompletion: 5.5e-08,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32000,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "microsoft/wizardlm-2-8x22b",
    name: "WizardLM-2 8x22B",
    created: 1713225600,
    description: "WizardLM-2 8x22B is Microsoft AI's most advanced Wizard model. It demonstrates highly competitive performance compared to leading proprietary models, and it consistently outperforms all existing state-of-the-art opensource models. It is an instruct finetune of [Mixtral 8x22B](/models/mistralai/mixtral-8x22b). To read more about the model release, [click here](https://wizardlm.github.io/WizardLM2/). #moe",
    contextLength: 65536,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Mistral",
    instructType: "vicuna",
    costPrompt: 5e-07,
    costCompletion: 5e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 65536,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "google/gemini-pro-1.5",
    name: "Google: Gemini Pro 1.5",
    created: 1712620800,
    description: "Google's latest multimodal model, supporting image and video in text or chat prompts. Optimized for language tasks including: - Code generation - Text generation - Text editing - Problem solving - Recommendations - Information extraction - Data extraction or generation - AI agents #multimodal",
    contextLength: 1000000,
    requestLimits: 0,
    modality: "text+image->text",
    tokenizer: "Gemini",
    instructType: "nan",
    costPrompt: 3.5e-06,
    costCompletion: 1.05e-05,
    costImage: 0.00263,
    costRequest: 0,
    contextLengthTopProvider: 1000000,
    maxCompletionTokensTopProvider: 8192,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "openai/gpt-4-turbo",
    name: "OpenAI: GPT-4 Turbo",
    created: 1712620800,
    description: "The latest GPT-4 Turbo model with vision capabilities. Vision requests can now use JSON mode and function calling. Training data: up to December 2023.",
    contextLength: 128000,
    requestLimits: 0,
    modality: "text+image->text",
    tokenizer: "GPT",
    instructType: "nan",
    costPrompt: 1e-05,
    costCompletion: 3e-05,
    costImage: 0.01445,
    costRequest: 0,
    contextLengthTopProvider: 128000,
    maxCompletionTokensTopProvider: 4096,
    isModerated: true,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "cohere/command-r-plus",
    name: "Cohere: Command R+",
    created: 1712188800,
    description: "Command R+ is a new, 104B-parameter LLM from Cohere. It's useful for roleplay, general consumer usecases, and Retrieval Augmented Generation (RAG). It offers multilingual support for ten key languages to facilitate global business operations. See benchmarks and the launch post [here](https://txt.cohere.com/command-r-plus-microsoft-azure/).",
    contextLength: 128000,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Cohere",
    instructType: "nan",
    costPrompt: 2.85e-06,
    costCompletion: 1.425e-05,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 128000,
    maxCompletionTokensTopProvider: 4000,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "cohere/command-r-plus-04-2024",
    name: "Cohere: Command R+ (04-2024)",
    created: 1712016000,
    description: "Command R+ is a new, 104B-parameter LLM from Cohere. It's useful for roleplay, general consumer usecases, and Retrieval Augmented Generation (RAG). It offers multilingual support for ten key languages to facilitate global business operations. See benchmarks and the launch post [here](https://txt.cohere.com/command-r-plus-microsoft-azure/).",
    contextLength: 128000,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Cohere",
    instructType: "nan",
    costPrompt: 2.85e-06,
    costCompletion: 1.425e-05,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 128000,
    maxCompletionTokensTopProvider: 4000,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "databricks/dbrx-instruct",
    name: "Databricks: DBRX 132B Instruct",
    created: 1711670400,
    description: "DBRX is a new open source large language model developed by Databricks. At 132B, it outperforms existing open source LLMs like Llama 2 70B and [Mixtral-8x7b](/models/mistralai/mixtral-8x7b) on standard industry benchmarks for language understanding, programming, math, and logic. It uses a fine-grained mixture-of-experts (MoE) architecture. 36B parameters are active on any input. It was pre-trained on 12T tokens of text and code data. Compared to other open MoE models like Mixtral-8x7B and Grok-1, DBRX is fine-grained, meaning it uses a larger number of smaller experts. See the launch announcement and benchmark results [here](https://www.databricks.com/blog/introducing-dbrx-new-state-art-open-llm). #moe",
    contextLength: 32768,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Other",
    instructType: "chatml",
    costPrompt: 1.08e-06,
    costCompletion: 1.08e-06,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32768,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "anthropic/claude-3-haiku",
    name: "Anthropic: Claude 3 Haiku",
    created: 1710288000,
    description: "Claude 3 Haiku is Anthropic's fastest and most compact model for near-instant responsiveness. Quick and accurate targeted performance. See the launch announcement and benchmark results [here](https://www.anthropic.com/news/claude-3-haiku) #multimodal",
    contextLength: 200000,
    requestLimits: 0,
    modality: "text+image->text",
    tokenizer: "Claude",
    instructType: "nan",
    costPrompt: 2.5e-07,
    costCompletion: 1.25e-06,
    costImage: 0.0004,
    costRequest: 0,
    contextLengthTopProvider: 200000,
    maxCompletionTokensTopProvider: 4096,
    isModerated: true,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "anthropic/claude-3-haiku:beta",
    name: "Anthropic: Claude 3 Haiku (self-moderated)",
    created: 1710288000,
    description: "Claude 3 Haiku is Anthropic's fastest and most compact model for near-instant responsiveness. Quick and accurate targeted performance. See the launch announcement and benchmark results [here](https://www.anthropic.com/news/claude-3-haiku) #multimodal _This is a faster endpoint, made available in collaboration with Anthropic, that is self-moderated: response moderation happens on the provider's side instead of OpenRouter's. For requests that pass moderation, it's identical to the [Standard](/models/anthropic/claude-3-haiku) variant._",
    contextLength: 200000,
    requestLimits: 0,
    modality: "text+image->text", 
    tokenizer: "Claude",
    instructType: "nan",
    costPrompt: 2.5e-07,
    costCompletion: 1.25e-06,
    costImage: 0.0004,
    costRequest: 0,
    contextLengthTopProvider: 200000,
    maxCompletionTokensTopProvider: 4096,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "anthropic/claude-3-sonnet",
    name: "Anthropic: Claude 3 Sonnet",
    created: 1709596800,
    description: "Claude 3 Sonnet is an ideal balance of intelligence and speed for enterprise workloads. Maximum utility at a lower price, dependable, balanced for scaled deployments. See the launch announcement and benchmark results [here](https://www.anthropic.com/news/claude-3-family) #multimodal",
    contextLength: 200000,
    requestLimits: 0,
    modality: "text+image->text",
    tokenizer: "Claude",
    instructType: "nan",
    costPrompt: 3e-06,
    costCompletion: 1.5e-05,
    costImage: 0.0048,
    costRequest: 0,
    contextLengthTopProvider: 200000,
    maxCompletionTokensTopProvider: 4096,
    isModerated: true,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "anthropic/claude-3-sonnet:beta",
    name: "Anthropic: Claude 3 Sonnet (self-moderated)",
    created: 1709596800,
    description: "Claude 3 Sonnet is an ideal balance of intelligence and speed for enterprise workloads. Maximum utility at a lower price, dependable, balanced for scaled deployments. See the launch announcement and benchmark results [here](https://www.anthropic.com/news/claude-3-family) #multimodal _This is a faster endpoint, made available in collaboration with Anthropic, that is self-moderated: response moderation happens on the provider's side instead of OpenRouter's. For requests that pass moderation, it's identical to the [Standard](/models/anthropic/claude-3-sonnet) variant._",
    contextLength: 200000,
    requestLimits: 0,
    modality: "text+image->text",
    tokenizer: "Claude",
    instructType: "nan",
    costPrompt: 3e-06,
    costCompletion: 1.5e-05,
    costImage: 0.0048,
    costRequest: 0,
    contextLengthTopProvider: 200000,
    maxCompletionTokensTopProvider: 4096,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "anthropic/claude-3-opus",
    name: "Anthropic: Claude 3 Opus",
    created: 1709596800,
    description: "Claude 3 Opus is Anthropic's most powerful model for highly complex tasks. It boasts top-level performance, intelligence, fluency, and understanding. See the launch announcement and benchmark results [here](https://www.anthropic.com/news/claude-3-family) #multimodal",
    contextLength: 200000,
    requestLimits: 0,
    modality: "text+image->text",
    tokenizer: "Claude",
    instructType: "nan",
    costPrompt: 1.5e-05,
    costCompletion: 7.5e-05,
    costImage: 0.024,
    costRequest: 0,
    contextLengthTopProvider: 200000,
    maxCompletionTokensTopProvider: 4096,
    isModerated: true,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "anthropic/claude-3-opus:beta",
    name: "Anthropic: Claude 3 Opus (self-moderated)",
    created: 1709596800,
    description: "Claude 3 Opus is Anthropic's most powerful model for highly complex tasks. It boasts top-level performance, intelligence, fluency, and understanding. See the launch announcement and benchmark results [here](https://www.anthropic.com/news/claude-3-family) #multimodal _This is a faster endpoint, made available in collaboration with Anthropic, that is self-moderated: response moderation happens on the provider's side instead of OpenRouter's. For requests that pass moderation, it's identical to the [Standard](/models/anthropic/claude-3-opus) variant._",
    contextLength: 200000,
    requestLimits: 0,
    modality: "text+image->text",
    tokenizer: "Claude",
    instructType: "nan",
    costPrompt: 1.5e-05,
    costCompletion: 7.5e-05,
    costImage: 0.024,
    costRequest: 0,
    contextLengthTopProvider: 200000,
    maxCompletionTokensTopProvider: 4096,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "mistralai/mistral-7b-instruct-v0.2",
    name: "Mistral: Mistral 7B Instruct v0.2",
    created: 1703721600,
    description: "A high-performing, industry-standard 7.3B parameter model, with optimizations for speed and context length. An improved version of [Mistral 7B Instruct](/modelsmistralai/mistral-7b-instruct-v0.1), with the following changes: - 32k context window (vs 8k context in v0.1) - Rope-theta = 1e6 - No Sliding-Window Attention",
    contextLength: 32768,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Mistral",
    instructType: "mistral",
    costPrompt: 1.8e-07,
    costCompletion: 1.8e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32768,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "cognitivecomputations/dolphin-mixtral-8x7b",
    name: "Dolphin 2.6 Mixtral 8x7B 🐬",
    created: 1703116800,
    description: "This is a 16k context fine-tune of [Mixtral-8x7b](/models/mistralai/mixtral-8x7b). It excels in coding tasks due to extensive training with coding data and is known for its obedience, although it lacks DPO tuning. The model is uncensored and is stripped of alignment and bias. It requires an external alignment layer for ethical use. Users are cautioned to use this highly compliant model responsibly, as detailed in a blog post about uncensored models at [erichartford.com/uncensored-models](https://erichartford.com/uncensored-models). #moe #uncensored",
    contextLength: 32768,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Mistral",
    instructType: "chatml",
    costPrompt: 5e-07,
    costCompletion: 5e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32768,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "google/gemini-pro",
    name: "Google: Gemini Pro 1.0",
    created: 1702425600,
    description: "Google's flagship text generation model. Designed to handle natural language tasks, multiturn text and code chat, and code generation. See the benchmarks and prompting guidelines from [Deepmind](https://deepmind.google/technologies/gemini/).",
    contextLength: 32760,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Gemini",
    instructType: "nan",
    costPrompt: 5e-07,
    costCompletion: 1.5e-06,
    costImage: 0.0025,
    costRequest: 0,
    contextLengthTopProvider: 32760,
    maxCompletionTokensTopProvider: 8192,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "mistralai/mistral-7b-instruct-v0.2",
    name: "Mistral: Mistral 7B Instruct v0.2",
    created: 1703721600,
    description: "A high-performing, industry-standard 7.3B parameter model, with optimizations for speed and context length. An improved version of [Mistral 7B Instruct](/modelsmistralai/mistral-7b-instruct-v0.1), with the following changes: - 32k context window (vs 8k context in v0.1) - Rope-theta = 1e6 - No Sliding-Window Attention",
    contextLength: 32768,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Mistral",
    instructType: "mistral",
    costPrompt: 1.8e-07,
    costCompletion: 1.8e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32768,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "cognitivecomputations/dolphin-mixtral-8x7b",
    name: "Dolphin 2.6 Mixtral 8x7B 🐬",
    created: 1703116800,
    description: "This is a 16k context fine-tune of [Mixtral-8x7b](/models/mistralai/mixtral-8x7b). It excels in coding tasks due to extensive training with coding data and is known for its obedience, although it lacks DPO tuning. The model is uncensored and is stripped of alignment and bias. It requires an external alignment layer for ethical use. Users are cautioned to use this highly compliant model responsibly, as detailed in a blog post about uncensored models at [erichartford.com/uncensored-models](https://erichartford.com/uncensored-models). #moe #uncensored",
    contextLength: 32768,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Mistral",
    instructType: "chatml",
    costPrompt: 5e-07,
    costCompletion: 5e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32768,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "google/gemini-pro",
    name: "Google: Gemini Pro 1.0",
    created: 1702425600,
    description: "Google's flagship text generation model. Designed to handle natural language tasks, multiturn text and code chat, and code generation. See the benchmarks and prompting guidelines from [Deepmind](https://deepmind.google/technologies/gemini/).",
    contextLength: 32760,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Gemini",
    instructType: "nan",
    costPrompt: 5e-07,
    costCompletion: 1.5e-06,
    costImage: 0.0025,
    costRequest: 0,
    contextLengthTopProvider: 32760,
    maxCompletionTokensTopProvider: 8192,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "cohere/command-r-03-2024",
    name: "Cohere: Command R (03-2024)",
    created: 1709341200,
    description: "Command-R is a 35B parameter model that performs conversational language tasks at a higher quality, more reliably, and with a longer context than previous models. It can be used for complex workflows like code generation, retrieval augmented generation (RAG), tool use, and agents. Read the launch post [here](https://txt.cohere.com/command-r/).",
    contextLength: 128000,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Cohere",
    instructType: "nan",
    costPrompt: 4.75e-07,
    costCompletion: 1.425e-06,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 128000,
    maxCompletionTokensTopProvider: 4000,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "mistralai/mistral-large",
    name: "Mistral Large",
    created: 1708905600,
    description: "This is Mistral AI's flagship model, Mistral Large 2 (version `mistral-large-2407`). It's a proprietary weights-available model and excels at reasoning, code, JSON, chat, and more. Read the launch announcement [here](https://mistral.ai/news/mistral-large-2407/). It is fluent in English, French, Spanish, German, and Italian, with high grammatical accuracy, and its long context window allows precise information recall from large documents.",
    contextLength: 128000,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Mistral",
    instructType: "nan",
    costPrompt: 2e-06,
    costCompletion: 6e-06,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 128000,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "nousresearch/hermes-2-mixtral-8x7b-dpo",
    name: "Nous: Hermes 2 Mixtral 8x7B DPO",
    created: 1705363200,
    description: "Nous Hermes 2 Mixtral 8x7B DPO is the new flagship Nous Research model trained over the [Mixtral 8x7B MoE LLM](/models/mistralai/mixtral-8x7b). The model was trained on over 1,000,000 entries of primarily [GPT-4](/models/openai/gpt-4) generated data, as well as other high quality data from open datasets across the AI landscape, achieving state of the art performance on a variety of tasks. #moe",
    contextLength: 32768,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Mistral",
    instructType: "chatml",
    costPrompt: 5.4e-07,
    costCompletion: 5.4e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32768,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "mistralai/mistral-tiny",
    name: "Mistral Tiny",
    created: 1704844800,
    description: "This model is currently powered by Mistral-7B-v0.2, and incorporates a 'better' fine-tuning than [Mistral 7B](/models/mistralai/mistral-7b-instruct-v0.1), inspired by community work. It's best used for large batch processing tasks where cost is a significant factor but reasoning capabilities are not crucial.",
    contextLength: 32000,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Mistral",
    instructType: "nan",
    costPrompt: 2.5e-07,
    costCompletion: 2.5e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32000,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "austism/chronos-hermes-13b",
    name: "Chronos Hermes 13B v2",
    created: 1704412800,
    description: "A 75/25 merge of [Chronos 13b v2](https://huggingface.co/elinas/chronos-13b-v2) and [Nous Hermes Llama2 13b](/models/nousresearch/nous-hermes-llama2-13b). This offers the imaginative writing style of Chronos while retaining coherency. Outputs are long and use exceptional prose. #merge",
    contextLength: 4096,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Llama2",
    instructType: "alpaca",
    costPrompt: 1.3e-07,
    costCompletion: 1.3e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 4096,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "nousresearch/nous-hermes-yi-34b",
    name: "Nous: Hermes 2 Yi 34B",
    created: 1704153600,
    description: "Nous Hermes 2 Yi 34B was trained on 1,000,000 entries of primarily GPT-4 generated data, as well as other high quality data from open datasets across the AI landscape. Nous-Hermes 2 on Yi 34B outperforms all Nous-Hermes & Open-Hermes models of the past, achieving new heights in all benchmarks for a Nous Research LLM as well as surpassing many popular finetunes.",
    contextLength: 4096,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Yi",
    instructType: "chatml",
    costPrompt: 7.2e-07,
    costCompletion: 7.2e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 4096,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "mistralai/mistral-small",
    name: "Mistral Small",
    created: 1704844800,
    description: "Cost-efficient, fast, and reliable option for use cases such as translation, summarization, and sentiment analysis.",
    contextLength: 32000,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Mistral",
    instructType: "nan",
    costPrompt: 2e-07,
    costCompletion: 6e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32000,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "openai/gpt-3.5-turbo-0613",
    name: "OpenAI: GPT-3.5 Turbo (older v0613)",
    created: 1706140800,
    description: gptDesc,
    contextLength: 4095,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "GPT",
    instructType: "nan",
    costPrompt: 1e-06,
    costCompletion: 2e-06,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 4095,
    maxCompletionTokensTopProvider: 4096,
    isModerated: true,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "openai/gpt-4-turbo-preview",
    name: "OpenAI: GPT-4 Turbo Preview",
    created: 1706140800,
    description: "The preview GPT-4 model with improved instruction following, JSON mode, reproducible outputs, parallel function calling, and more. Training data: up to Dec 2023.**Note:** heavily rate limited by OpenAI while in preview.",
    contextLength: 128000,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "GPT",
    instructType: "nan",
    costPrompt: 1e-05,
    costCompletion: 3e-05,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 128000,
    maxCompletionTokensTopProvider: 4096,
    isModerated: true,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "mistralai/mistral-medium",
    name: "Mistral Medium",
    created: 1704844800,
    description: "This is Mistral AI's closed-source, medium-sized model. It's powered by a closed-source prototype and excels at reasoning, code, JSON, chat, and more. In benchmarks, it compares with many of the flagship models of other companies.",
    contextLength: 32000,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Mistral",
    instructType: "nan",
    costPrompt: 2.75e-06,
    costCompletion: 8.1e-06,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32000,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "google/palm-2-codechat-bison-32k",
    name: "Google: PaLM 2 Code Chat 32k",
    created: 1698969600,
    description: "PaLM 2 fine-tuned for chatbot conversations that help with code-related questions.",
    contextLength: 32760,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "PaLM",
    instructType: "nan",
    costPrompt: 1e-06,
    costCompletion: 2e-06,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32768,
    maxCompletionTokensTopProvider: 8192,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "google/palm-2-chat-bison-32k",
    name: "Google: PaLM 2 Chat 32k",
    created: 1698969600,
    description: "PaLM 2 is a language model by Google with improved multilingual, reasoning and coding capabilities.",
    contextLength: 32760,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "PaLM",
    instructType: "nan",
    costPrompt: 1e-06,
    costCompletion: 2e-06,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32768,
    maxCompletionTokensTopProvider: 8192,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "jondurbin/airoboros-l2-70b",
    name: "Airoboros 70B",
    created: 1698537600,
    description: "A Llama 2 70B fine-tune using synthetic data (the Airoboros dataset). Currently based on [jondurbin/airoboros-l2-70b](https://huggingface.co/jondurbin/airoboros-l2-70b-2.2.1), but might get updated in the future.",
    contextLength: 4096,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Llama2",
    instructType: "airoboros",
    costPrompt: 5e-07,
    costCompletion: 5e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 4096,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "google/gemini-pro-vision",
    name: "Google: Gemini Pro Vision 1.0",
    created: 1702425600,
    description: "Google's flagship multimodal model, supporting image and video in text or chat prompts for a text or code response. See the benchmarks and prompting guidelines from [Deepmind](https://deepmind.google/technologies/gemini/). #multimodal",
    contextLength: 16384,
    requestLimits: 0,
    modality: "text+image->text",
    tokenizer: "Gemini",
    instructType: "nan",
    costPrompt: 5e-07,
    costCompletion: 1.5e-06,
    costImage: 0.0025,
    costRequest: 0,
    contextLengthTopProvider: 16384,
    maxCompletionTokensTopProvider: 2048,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "mistralai/mixtral-8x7b-instruct",
    name: "Mixtral 8x7B Instruct",
    created: 1702166400,
    description: "A pretrained generative Sparse Mixture of Experts, by Mistral AI, for chat and instruction use. Incorporates 8 experts (feed-forward networks) for a total of 47 billion parameters. Instruct model fine-tuned by Mistral. #moe",
    contextLength: 32768,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Mistral",
    instructType: "mistral",
    costPrompt: 2.4e-07,
    costCompletion: 2.4e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32768,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "mistralai/mixtral-8x7b",
    name: "Mixtral 8x7B (base)",
    created: 1702166400,
    description: "A pretrained generative Sparse Mixture of Experts, by Mistral AI. Incorporates 8 experts (feed-forward networks) for a total of 47B parameters. Base model (not fine-tuned for instructions) - see [Mixtral 8x7B Instruct](/models/mistralai/mixtral-8x7b-instruct) for an instruct-tuned model. #moe",
    contextLength: 32768,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Mistral",
    instructType: "none",
    costPrompt: 5.4e-07,
    costCompletion: 5.4e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32768,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "gryphe/mythomist-7b",
    name: "MythoMist 7B",
    created: 1701907200,
    description: "From the creator of [MythoMax](/models/gryphe/mythomax-l2-13b), merges a suite of models to reduce word anticipation, ministrations, and other undesirable words in ChatGPT roleplaying data. It combines [Neural Chat 7B](/models/intel/neural-chat-7b), Airoboros 7b, [Toppy M 7B](/models/undi95/toppy-m-7b), [Zepher 7b beta](/models/huggingfaceh4/zephyr-7b-beta), [Nous Capybara 34B](/models/nousresearch/nous-capybara-34b), [OpenHeremes 2.5](/models/teknium/openhermes-2.5-mistral-7b), and many others. #merge",
    contextLength: 32768,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Mistral",
    instructType: "alpaca",
    costPrompt: 3.75e-07,
    costCompletion: 3.75e-07,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 32768,
    maxCompletionTokensTopProvider: 2048,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "openchat/openchat-7b",
    name: "OpenChat 3.5 7B",
    created: 1701129600,
    description: "OpenChat 7B is a library of open-source language models, fine-tuned with 'C-RLFT (Conditioned Reinforcement Learning Fine-Tuning)' - a strategy inspired by offline reinforcement learning. It has been trained on mixed-quality data without preference labels. - For OpenChat fine-tuned on Mistral 7B, check out [OpenChat 7B](/models/openchat/openchat-7b). - For OpenChat fine-tuned on Llama 8B, check out [OpenChat 8B](/models/openchat/openchat-8b). #open-source",
    contextLength: 8192,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Mistral",
    instructType: "openchat",
    costPrompt: 5.5e-08,
    costCompletion: 5.5e-08,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 8192,
    maxCompletionTokensTopProvider: 0,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "neversleep/noromaid-20b",
    name: "Noromaid 20B",
    created: 1700956800,
    description: "A collab between IkariDev and Undi. This merge is suitable for RP, ERP, and general knowledge. #merge #uncensored",
    contextLength: 8192,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Llama2",
    instructType: "alpaca",
    costPrompt: 1.5e-06,
    costCompletion: 2.25e-06,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 8192,
    maxCompletionTokensTopProvider: 2048,
    isModerated: false,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  },
  {
    id: "anthropic/claude-instant-1.1",
    name: "Anthropic: Claude Instant v1.1",
    created: 1700611200,
    description: claudeDesc,
    contextLength: 100000,
    requestLimits: 0,
    modality: "text->text",
    tokenizer: "Claude",
    instructType: "claude",
    costPrompt: 8e-07,
    costCompletion: 2.4e-06,
    costImage: 0,
    costRequest: 0,
    contextLengthTopProvider: 100000,
    maxCompletionTokensTopProvider: 2048,
    isModerated: true,
    preferredProvider: "openrouter",
    type: "llm",
    incompatible: []
  }
];

export const providers = [
  'openrouter',
  'replicate', 
  'mistral',
  'huggingface',
  'openai'
];

export function modelFind(field: any, head: ModelHead): Model | undefined {
  return models.find(model => model[Object.keys(model)[head]] === field);
}

export function modelByName(modelName: string): Model | undefined {
  return modelFind(modelName, ModelHead.name);
}

export function modelById(modelId: string): Model | undefined {
  return modelFind(modelId, ModelHead.id);
}

export function validateProvider(provider: string, model: string): string {
  if (!provider) {
    const foundModel = modelByName(model);
    return foundModel ? foundModel.preferredProvider : 'openrouter';
  }
  
  const providerIndex = parseInt(provider);
  if (!isNaN(providerIndex) && providerIndex >= 0 && providerIndex < providers.length) {
    return providers[providerIndex];
  }
  
  return provider;
}

// Load voice samples from CSV
export const voiceSamples: { [key: string]: string } = {};
try {
  const samplesData = readFileSync('samples.csv', 'utf-8');
  const lines = samplesData.split('\n').slice(1); // Skip header
  lines.forEach(line => {
    const [voiceName, url] = line.split(',');
    if (voiceName && url) {
      voiceSamples[voiceName.trim()] = url.trim();
    }
  });
} catch (error) {
  console.error('Error loading voice samples:', error);
}

export function listAll(): void {
  console.log("\nmodels:\n");
  models.forEach(model => {
    console.log(`"${model.name}": "${model.id}",`);
  });
  
  console.log("\nproviders:\n");
  providers.forEach((provider, index) => {
    console.log(`${index}. ${provider}`);
  });
}
